name: test-snap-lukewh-2
version: 0.0.4
summary: Just a test python snap
description: >
  Just a test python snap

confinement: strict
base: core18

parts:
  test-snap-lukewh-2:
    plugin: python
    python-version: python3
    source: .

apps:
  test-snap-lukewh-2:
    command: python3 test_snap.py --swallow-this-arg
